SHEET_ID = "1lkgUQv9adCIvFD2p9ZJ_t0ev4Zq1U6OUxaZwBwypjTU"

[gcp_service_account]
type = "service_account"
project_id = "prospeccion-484418"
private_key_id = "7e1f8f94e024d651db0ad0f326262221e2e060d5"
private_key = """-----BEGIN PRIVATE KEY-----
(PEGA AQU√ç LA CLAVE PRIVADA COMPLETA DESDE TU ARCHIVO JSON)
-----END PRIVATE KEY-----"""
client_email = "streamlit-agent-hvac@prospeccion-484418.iam.gserviceaccount.com"
client_id = "101136848183478174604"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-agent-hvac@prospeccion-484418.iam.gserviceaccount.com"
