SHEET_ID = "1lkgUQv9adCIvFD2p9ZJ_t0ev4Zq1U6OUxaZwBwypjTU"

[gcp_service_account]
type = "service_account"
project_id = "prospeccion-484418"
private_key_id = "7e1f8f94e024d651db0ad0f326262221e2e060d5"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDZ8hz0tC5pcK4u
eB4MW/hEWlLiesaPHbp9YXkS+xCSbWbl088FesZBhUW7k1rci81BqZA8PexUIsTZ
18fWfdrGfSfsoFoWyFaLtJL3wRE0DMi+Mvy5r6+hJQ6uHA4ypmReNG2lBspYcMLn
LkjfbKciMqK/nGNmsZRdGuFkr2KjOWxAIvhW3wnFCe3htdkNsQYMoRxD736nDnlz
goK4HQOw2qiqfRK9+t8Fn+9p/zWZNjZPzY5c7xXfUmHWjEqMvXHCVFMMjaJQ0Suk
BVuiE6mlIUDHj3vvFdBjfNdp/mgRNF3OFZZ9ZaW5rvtgI1OxW85jsn/9Wk+pYHlY
LaVFJgI9AgMBAAECggEAJTnfjESCcOwYNEO8DixfWX18DscdxzAyvFu7zGwpxnj9
TGBDShJQbryOzp06tdUDOCX4RvHkvfI6YWMj9RUGG0UhXp99A8swTSiIudy2TYep
eiNHW4gQnZuwyDhujGQzXIvj9n4UbcrE36veMptiaMrxVX0m1VGbn9OJkCMM3AgP
8vMSLeHRUsrLEnSX3/w8mB/DhN3tLQYHAkaeH0g/R8V+FhbUQVtdnacDd3Rp1B+l
SgMrQLKTo8OAx8pBuSLQ6cHBD0HpwRk0+jZsJf2BiEwOBySjhCajDkU7kFydR8FC
e0kLwLDbrYA/pkOhhpg+B12TG+vZirC3t6ihgcvkmQKBgQD+zBWAFw5WzCdwbFor
MkrBWIbyo8dxyaEjedEqlLSLyXS1lj5BuPpOjSKrg+CRsRUMFfbeYCZ/uOiK3pPz
1hcl2GFiin7tW19sUN+BkAir0Q0im0sYxF5ZjblT3tIWv8JTU5fQlwMguBV5reql
KFGj7QP6u9QJ9wPbx39a6rJ5UwKBgQDa+X69J+TXpAlfA3nnqFo5zzeUr4mQer2y
ughr/cGxH2kb14dxGd4lgpVMWZEvw4E61kE62nu81lgsDxcWGTRQeYH94ujzAM+x
bviENZcCRQRgVF1kM2dNX/rQ2foaygAlXETN9LucO7w95kniZd8z8MSCkaMN4g+4
IXtbRFPULwKBgAi6av4hTA9zHOLAA3K5XVA0PSMwsxNVydxSPvULdQfY1dOmmulb
cc+hDA/+C4JSI5tvYS6K8qaraePf7geLTO2x9NwQTHrLB4DJYG6qxXFFTwLhePgX
OfgtX6zc1CuNVBXQpkGx+pxzUeECMSiJMgrAgsNjDcdtm8c6lUVDBuwbAoGAUplE
PnPa9aCxzD5ScJjnl+DbVWG1oWM7RTy5SosI0hhIHLF7LKWWT03npUov4vV7PMdv
CZU6kavEzLHQgox1WFnNOAis2GUY8xQp+C0Czl9cXD3WkKJ3OA+ZW8iteAd0cKNS
bOIBFtjNlAfXHOhSfpQ2fA4VlHoOdeVjU7T9bg8CgYEAx10xgoOZDA+X3TzlRXnw
BmJgMNsXHhejqUDhRnC9goTQTE4jblhiwUsZLrGumDXMyJ3Yn8qhUyo+99NxpbCh
H7UlJAQcfC+/uhHHDMxMyeCW1E+lXVRCMD1dytMpjxmbT4aZOiAynuaCQ9MzYBHS
Qw9UjH1tReRJME0DHjGKJ3E=
-----END PRIVATE KEY-----"""
client_email = "streamlit-agent-hvac@prospeccion-484418.iam.gserviceaccount.com"
client_id = "101136848183478174604"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-agent-hvac@prospeccion-484418.iam.gserviceaccount.com"

client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-agent-hvac@prospeccion-484418.iam.gserviceaccount.com"
